site_name: frameio-kit
site_url: "https://billyshambrook.github.io/frameio-kit/"
repo_name: billyshambrook/frameio-kit
repo_url: https://github.com/billyshambrook/frameio-kit
watch: [mkdocs.yml, docs, src]
copyright: Copyright &copy; 2025 Billy Shambrook
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.instant.preview
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow

nav:
  - Home: index.md
  - Usage:
      - Getting Started: usage/getting_started.md
      - Webhooks: usage/webhooks.md
      - Custom Actions: usage/custom_actions.md
      - Client API: usage/client_api.md
      - Middleware: usage/middleware.md
  - API Reference: api_reference.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            members_order: source
            backlinks: tree
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            # filters: ["!^_"]
            # heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            show_root_toc_entry: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
