name: 💡 Enhancement Request
description: Suggest an idea or improvement for frameio-kit
labels: [enhancement, pending]

body:
  - type: markdown
    attributes:
      value: Thanks for contributing to frameio-kit! 🙏

  - type: markdown
    attributes:
      value: |
        ### Before you submit

        To help us evaluate your enhancement request:

        - 🔍 **Check if this has already been requested** - search existing issues first
        - 💭 **Think about the broader impact** - how would this affect other users?
        - 📋 **Consider implementation complexity** - is this a small change or a major feature?

        Thanks for helping to make frameio-kit better! 🚀

  - type: textarea
    id: description
    attributes:
      label: Enhancement
      description: |
        Please describe the enhancement:

        - What problem or use case would it solve?
        - How would it improve your workflow or experience with frameio-kit?
        - Are there any alternative solutions you've considered?
    validations:
      required: true
