name: Publish Framekit to PyPI
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write # For PyPI's trusted publishing
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: "Install uv"
        uses: astral-sh/setup-uv@v6
      
      - name: Update version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}  # Remove 'v' prefix if present
          sed -i -e "s/^version = \"0.0.0\"/version = \"$VERSION\"/" pyproject.toml

      - name: Build
        run: uv build

      - name: Publish to PyPI
        run: uv publish
